### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'

### ISSUE THREAD

**Issue by shobhitpuri** [googlesamples/android-play-publisher-api#25]
It used to build fine but recently it started giving following exceptions both for list_apks.py and upload_apk.py at following lines:

```
... 
credentials = client.SignedJwtAssertionCredentials(
      SERVICE_ACCOUNT_EMAIL,
      key,
      scope='https://www.googleapis.com/auth/androidpublisher')
  http = httplib2.Http()
  http = credentials.authorize(http)
```

Here is the exceptions:

```
Determining latest version for my.package.name...
error	25-Feb-2016 06:30:52	Traceback (most recent call last):
error	25-Feb-2016 06:30:52	  File "list_apks.py", line 80, in <module>
error	25-Feb-2016 06:30:52	    main()
error	25-Feb-2016 06:30:52	  File "list_apks.py", line 46, in main
error	25-Feb-2016 06:30:52	    credentials = client.SignedJwtAssertionCredentials(
error	25-Feb-2016 06:30:52	AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'
build	25-Feb-2016 06:30:52	Found latest APK version: 
build	25-Feb-2016 06:30:52	Generated new APK version: 1
```

```
25-Feb-2016 06:33:30 	Uploading APK...
25-Feb-2016 06:33:30 	Traceback (most recent call last):
25-Feb-2016 06:33:30 	  File "upload_apk.py", line 115, in <module>
25-Feb-2016 06:33:30 	    main(sys.argv)
25-Feb-2016 06:33:30 	  File "upload_apk.py", line 62, in main
25-Feb-2016 06:33:30 	    credentials = client.SignedJwtAssertionCredentials(
25-Feb-2016 06:33:30 	AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'
```

**Comment by gimmeshelter** [comment]
They moved it.  The examples have yet to be updated.
https://github.com/google/oauth2client/issues/401

**Comment by rusma** [comment]
**First add:**

`from oauth2client.service_account import ServiceAccountCredentials
`

**Replace:**

`f = file('key.p12', 'rb')`
`key = f.read()`
` f.close()`

`credentials = client.SignedJwtAssertionCredentials(
      SERVICE_ACCOUNT_EMAIL,
      key,
      scope='https://www.googleapis.com/auth/androidpublisher')`

**With:**

`credentials = ServiceAccountCredentials.from_json_keyfile_name('key_120117.json', https://www.googleapis.com/auth/androidpublisher')`

**Instead of using a .p12 file, I generated a json version of the key from my Google API console. If you still want to use a .p12 file check documentation of the ServiceAccountCredentials, there is also a method for that**

**Comment by pcosta21** [comment]
Hey guys, I had the same problem and I've solved with the comment above.

https://github.com/googlesamples/android-play-publisher-api/blob/master/v3/python/basic_list_apks_service_account.py

Is there a reason this code isn't updated yet?
